apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      access_key: minio123
      secret_key: toomanysecrets
