apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm
      endpoint: s3-minio.apps.ocp4-927mp-ipi.azure.opentlc.com:443
      insecure: false
      access_key: minio123
      secret_key: toomanysecrets
